INSERT INTO City(city_name,state_name,population) VALUES ('New York','NY',18713220);
INSERT INTO City(city_name,state_name,population) VALUES ('Los Angeles','CA',12750807);
INSERT INTO City(city_name,state_name,population) VALUES ('Chicago','IL',8604203);
INSERT INTO City(city_name,state_name,population) VALUES ('Miami','FL',6445545);
INSERT INTO City(city_name,state_name,population) VALUES ('Dallas','TX',5743938);
INSERT INTO City(city_name,state_name,population) VALUES ('Philadelphia','PA',5649300);
INSERT INTO City(city_name,state_name,population) VALUES ('Houston','TX',5464251);
INSERT INTO City(city_name,state_name,population) VALUES ('Atlanta','GA',5449398);
INSERT INTO City(city_name,state_name,population) VALUES ('Washington','DC',5379184);
INSERT INTO City(city_name,state_name,population) VALUES ('Boston','MA',4688346);
INSERT INTO City(city_name,state_name,population) VALUES ('Phoenix','AZ',4219697);
INSERT INTO City(city_name,state_name,population) VALUES ('Seattle','WA',3789215);
INSERT INTO City(city_name,state_name,population) VALUES ('San Francisco','CA',3592294);
INSERT INTO City(city_name,state_name,population) VALUES ('Detroit','MI',3506126);
INSERT INTO City(city_name,state_name,population) VALUES ('San Diego','CA',3220118);
INSERT INTO City(city_name,state_name,population) VALUES ('Minneapolis','MN',2977172);
INSERT INTO City(city_name,state_name,population) VALUES ('Tampa','FL',2908063);
INSERT INTO City(city_name,state_name,population) VALUES ('Denver','CO',2876625);
INSERT INTO City(city_name,state_name,population) VALUES ('Brooklyn','NY',2559903);
INSERT INTO City(city_name,state_name,population) VALUES ('Queens','NY',2230722);
INSERT INTO City(city_name,state_name,population) VALUES ('Riverside','CA',2107852);
INSERT INTO City(city_name,state_name,population) VALUES ('Baltimore','MD',2106068);
INSERT INTO City(city_name,state_name,population) VALUES ('Las Vegas','NV',2104198);
INSERT INTO City(city_name,state_name,population) VALUES ('Portland','OR',2074775);
INSERT INTO City(city_name,state_name,population) VALUES ('San Antonio','TX',2049293);
INSERT INTO City(city_name,state_name,population) VALUES ('St. Louis','MO',2024074);
INSERT INTO City(city_name,state_name,population) VALUES ('Sacramento','CA',1898019);
INSERT INTO City(city_name,state_name,population) VALUES ('Orlando','FL',1822394);
INSERT INTO City(city_name,state_name,population) VALUES ('San Jose','CA',1798103);
INSERT INTO City(city_name,state_name,population) VALUES ('Cleveland','OH',1710093);
INSERT INTO City(city_name,state_name,population) VALUES ('Pittsburgh','PA',1703266);
INSERT INTO City(city_name,state_name,population) VALUES ('Austin','TX',1687311);
INSERT INTO City(city_name,state_name,population) VALUES ('Cincinnati','OH',1662691);
INSERT INTO City(city_name,state_name,population) VALUES ('Kansas City','MO',1636715);
INSERT INTO City(city_name,state_name,population) VALUES ('Manhattan','NY',1628706);
INSERT INTO City(city_name,state_name,population) VALUES ('Indianapolis','IN',1588961);
INSERT INTO City(city_name,state_name,population) VALUES ('Columbus','OH',1562009);
INSERT INTO City(city_name,state_name,population) VALUES ('Charlotte','NC',1512923);
INSERT INTO City(city_name,state_name,population) VALUES ('Virginia Beach','VA',1478868);
INSERT INTO City(city_name,state_name,population) VALUES ('Bronx','NY',1418207);
INSERT INTO City(city_name,state_name,population) VALUES ('Milwaukee','WI',1365787);
INSERT INTO City(city_name,state_name,population) VALUES ('Providence','RI',1203230);
INSERT INTO City(city_name,state_name,population) VALUES ('Jacksonville','FL',1181496);
INSERT INTO City(city_name,state_name,population) VALUES ('Salt Lake City','UT',1098526);
INSERT INTO City(city_name,state_name,population) VALUES ('Nashville','TN',1081903);
INSERT INTO City(city_name,state_name,population) VALUES ('Richmond','VA',1075798);
INSERT INTO City(city_name,state_name,population) VALUES ('Memphis','TN',1066967);
INSERT INTO City(city_name,state_name,population) VALUES ('Raleigh','NC',1038738);
INSERT INTO City(city_name,state_name,population) VALUES ('New Orleans','LA',1020886);
INSERT INTO City(city_name,state_name,population) VALUES ('Louisville','KY',1005654);
INSERT INTO City(city_name,state_name,population) VALUES ('Oklahoma City','OK',972943);
INSERT INTO City(city_name,state_name,population) VALUES ('Bridgeport','CT',924449);
INSERT INTO City(city_name,state_name,population) VALUES ('Buffalo','NY',914341);
INSERT INTO City(city_name,state_name,population) VALUES ('Fort Worth','TX',909585);
INSERT INTO City(city_name,state_name,population) VALUES ('Hartford','CT',905152);
INSERT INTO City(city_name,state_name,population) VALUES ('Tucson','AZ',888486);
INSERT INTO City(city_name,state_name,population) VALUES ('Omaha','NE',847819);
INSERT INTO City(city_name,state_name,population) VALUES ('El Paso','TX',843386);
INSERT INTO City(city_name,state_name,population) VALUES ('Honolulu','HI',820987);
INSERT INTO City(city_name,state_name,population) VALUES ('McAllen','TX',804114);
INSERT INTO City(city_name,state_name,population) VALUES ('Albuquerque','NM',761195);
INSERT INTO City(city_name,state_name,population) VALUES ('Birmingham','AL',739573);
INSERT INTO City(city_name,state_name,population) VALUES ('Sarasota','FL',722243);
INSERT INTO City(city_name,state_name,population) VALUES ('Dayton','OH',718353);
INSERT INTO City(city_name,state_name,population) VALUES ('Rochester','NY',703952);
INSERT INTO City(city_name,state_name,population) VALUES ('Fresno','CA',703498);
INSERT INTO City(city_name,state_name,population) VALUES ('Allentown','PA',683794);
INSERT INTO City(city_name,state_name,population) VALUES ('Tulsa','OK',671033);
INSERT INTO City(city_name,state_name,population) VALUES ('Cape Coral','FL',668382);
INSERT INTO City(city_name,state_name,population) VALUES ('Concord','CA',652308);
INSERT INTO City(city_name,state_name,population) VALUES ('Colorado Springs','CO',642413);
INSERT INTO City(city_name,state_name,population) VALUES ('Charleston','SC',628377);
INSERT INTO City(city_name,state_name,population) VALUES ('Springfield','MA',623401);
INSERT INTO City(city_name,state_name,population) VALUES ('Grand Rapids','MI',609314);
INSERT INTO City(city_name,state_name,population) VALUES ('Mission Viejo','CA',590249);
INSERT INTO City(city_name,state_name,population) VALUES ('Albany','NY',586383);
INSERT INTO City(city_name,state_name,population) VALUES ('Knoxville','TN',586048);
INSERT INTO City(city_name,state_name,population) VALUES ('Bakersfield','CA',579295);
INSERT INTO City(city_name,state_name,population) VALUES ('Ogden','UT',578523);
INSERT INTO City(city_name,state_name,population) VALUES ('Baton Rouge','LA',570308);
INSERT INTO City(city_name,state_name,population) VALUES ('Akron','OH',565208);
INSERT INTO City(city_name,state_name,population) VALUES ('New Haven','CT',564830);
INSERT INTO City(city_name,state_name,population) VALUES ('Columbia','SC',560041);
INSERT INTO City(city_name,state_name,population) VALUES ('Mesa','AZ',518012);
INSERT INTO City(city_name,state_name,population) VALUES ('Palm Bay','FL',507002);
INSERT INTO City(city_name,state_name,population) VALUES ('Provo','UT',500617);
INSERT INTO City(city_name,state_name,population) VALUES ('Worcester','MA',498328);
INSERT INTO City(city_name,state_name,population) VALUES ('Murrieta','CA',496046);
INSERT INTO City(city_name,state_name,population) VALUES ('Greenville','SC',484465);
INSERT INTO City(city_name,state_name,population) VALUES ('Wichita','KS',482249);
INSERT INTO City(city_name,state_name,population) VALUES ('Toledo','OH',482111);
INSERT INTO City(city_name,state_name,population) VALUES ('Staten Island','NY',476143);
INSERT INTO City(city_name,state_name,population) VALUES ('Des Moines','IA',473957);
INSERT INTO City(city_name,state_name,population) VALUES ('Long Beach','CA',462628);
INSERT INTO City(city_name,state_name,population) VALUES ('Port St. Lucie','FL',461152);
INSERT INTO City(city_name,state_name,population) VALUES ('Denton','TX',457177);
INSERT INTO City(city_name,state_name,population) VALUES ('Madison','WI',447245);
INSERT INTO City(city_name,state_name,population) VALUES ('Reno','NV',445020);
INSERT INTO City(city_name,state_name,population) VALUES ('Harrisburg','PA',442289);
INSERT INTO City(city_name,state_name,population) VALUES ('Little Rock','AR',439815);
INSERT INTO City(city_name,state_name,population) VALUES ('Oakland','CA',433031);
INSERT INTO City(city_name,state_name,population) VALUES ('Durham','NC',424700);
INSERT INTO City(city_name,state_name,population) VALUES ('Winston-Salem','NC',422269);
INSERT INTO City(city_name,state_name,population) VALUES ('Bonita Springs','FL',421291);
INSERT INTO City(city_name,state_name,population) VALUES ('Indio','CA',417059);
INSERT INTO City(city_name,state_name,population) VALUES ('Palm Coast','FL',417007);
INSERT INTO City(city_name,state_name,population) VALUES ('Chattanooga','TN',415501);
INSERT INTO City(city_name,state_name,population) VALUES ('Spokane','WA',412275);
INSERT INTO City(city_name,state_name,population) VALUES ('Syracuse','NY',404223);
INSERT INTO City(city_name,state_name,population) VALUES ('Lancaster','PA',401524);
INSERT INTO City(city_name,state_name,population) VALUES ('Arlington','TX',398854);
INSERT INTO City(city_name,state_name,population) VALUES ('Stockton','CA',397264);
INSERT INTO City(city_name,state_name,population) VALUES ('Poughkeepsie','NY',394760);
INSERT INTO City(city_name,state_name,population) VALUES ('Augusta','GA',390809);
INSERT INTO City(city_name,state_name,population) VALUES ('Boise','ID',389280);
INSERT INTO City(city_name,state_name,population) VALUES ('Oxnard','CA',387647);
INSERT INTO City(city_name,state_name,population) VALUES ('Scranton','PA',384250);
INSERT INTO City(city_name,state_name,population) VALUES ('Modesto','CA',383134);
INSERT INTO City(city_name,state_name,population) VALUES ('Kissimmee','FL',382720);
INSERT INTO City(city_name,state_name,population) VALUES ('Aurora','CO',379289);
INSERT INTO City(city_name,state_name,population) VALUES ('Youngstown','OH',378732);
INSERT INTO City(city_name,state_name,population) VALUES ('Fayetteville','AR',351246);
INSERT INTO City(city_name,state_name,population) VALUES ('Anaheim','CA',350365);
INSERT INTO City(city_name,state_name,population) VALUES ('Pensacola','FL',346921);
INSERT INTO City(city_name,state_name,population) VALUES ('Victorville','CA',346789);
INSERT INTO City(city_name,state_name,population) VALUES ('Lancaster','CA',343304);
INSERT INTO City(city_name,state_name,population) VALUES ('Greensboro','NC',343090);
INSERT INTO City(city_name,state_name,population) VALUES ('Corpus Christi','TX',342464);
INSERT INTO City(city_name,state_name,population) VALUES ('Fort Wayne','IN',334122);
INSERT INTO City(city_name,state_name,population) VALUES ('Santa Ana','CA',332318);
INSERT INTO City(city_name,state_name,population) VALUES ('Flint','MI',332190);
INSERT INTO City(city_name,state_name,population) VALUES ('Fayetteville','NC',327435);
INSERT INTO City(city_name,state_name,population) VALUES ('Jackson','MS',325350);
INSERT INTO City(city_name,state_name,population) VALUES ('Santa Rosa','CA',324634);
INSERT INTO City(city_name,state_name,population) VALUES ('Lansing','MI',324286);
INSERT INTO City(city_name,state_name,population) VALUES ('San Juan','PR',323279);
INSERT INTO City(city_name,state_name,population) VALUES ('Lexington','KY',323152);
INSERT INTO City(city_name,state_name,population) VALUES ('Ann Arbor','MI',322267);
INSERT INTO City(city_name,state_name,population) VALUES ('Henderson','NV',320189);
INSERT INTO City(city_name,state_name,population) VALUES ('Huntsville','AL',319249);
INSERT INTO City(city_name,state_name,population) VALUES ('Mobile','AL',315502);
INSERT INTO City(city_name,state_name,population) VALUES ('Fort Collins','CO',312666);
INSERT INTO City(city_name,state_name,population) VALUES ('Asheville','NC',312507);
INSERT INTO City(city_name,state_name,population) VALUES ('Santa Clarita','CA',312446);
INSERT INTO City(city_name,state_name,population) VALUES ('St. Paul','MN',308096);
INSERT INTO City(city_name,state_name,population) VALUES ('Antioch','CA',302419);
INSERT INTO City(city_name,state_name,population) VALUES ('Lakeland','FL',302284);
INSERT INTO City(city_name,state_name,population) VALUES ('Trenton','NJ',290716);
INSERT INTO City(city_name,state_name,population) VALUES ('Lincoln','NE',289490);
INSERT INTO City(city_name,state_name,population) VALUES ('Springfield','MO',288090);
INSERT INTO City(city_name,state_name,population) VALUES ('Anchorage','AK',288000);
INSERT INTO City(city_name,state_name,population) VALUES ('Plano','TX',287677);
INSERT INTO City(city_name,state_name,population) VALUES ('Irvine','CA',287401);
INSERT INTO City(city_name,state_name,population) VALUES ('Davenport','IA',285362);
INSERT INTO City(city_name,state_name,population) VALUES ('Rockford','IL',282762);
INSERT INTO City(city_name,state_name,population) VALUES ('Newark','NJ',282011);
INSERT INTO City(city_name,state_name,population) VALUES ('South Bend','IN',280498);
INSERT INTO City(city_name,state_name,population) VALUES ('Shreveport','LA',280062);
INSERT INTO City(city_name,state_name,population) VALUES ('Round Lake Beach','IL',279381);
INSERT INTO City(city_name,state_name,population) VALUES ('Savannah','GA',276295);
INSERT INTO City(city_name,state_name,population) VALUES ('Myrtle Beach','SC',275579);
INSERT INTO City(city_name,state_name,population) VALUES ('Chula Vista','CA',274492);
INSERT INTO City(city_name,state_name,population) VALUES ('Eugene','OR',273439);
INSERT INTO City(city_name,state_name,population) VALUES ('Canton','OH',269418);
INSERT INTO City(city_name,state_name,population) VALUES ('Lubbock','TX',267648);
INSERT INTO City(city_name,state_name,population) VALUES ('Reading','PA',267155);
INSERT INTO City(city_name,state_name,population) VALUES ('Winter Haven','FL',267069);
INSERT INTO City(city_name,state_name,population) VALUES ('Salem','OR',266804);
INSERT INTO City(city_name,state_name,population) VALUES ('St. Petersburg','FL',265351);
INSERT INTO City(city_name,state_name,population) VALUES ('Lafayette','LA',264357);
INSERT INTO City(city_name,state_name,population) VALUES ('Laredo','TX',262491);
INSERT INTO City(city_name,state_name,population) VALUES ('Jersey City','NJ',262075);
INSERT INTO City(city_name,state_name,population) VALUES ('Concord','NC',261801);
INSERT INTO City(city_name,state_name,population) VALUES ('Columbus','GA',261445);
INSERT INTO City(city_name,state_name,population) VALUES ('Chandler','AZ',261165);
INSERT INTO City(city_name,state_name,population) VALUES ('McKinney','TX',258277);
INSERT INTO City(city_name,state_name,population) VALUES ('Scottsdale','AZ',258069);
INSERT INTO City(city_name,state_name,population) VALUES ('Killeen','TX',258009);
INSERT INTO City(city_name,state_name,population) VALUES ('Tallahassee','FL',257601);
INSERT INTO City(city_name,state_name,population) VALUES ('Peoria','IL',256286);
INSERT INTO City(city_name,state_name,population) VALUES ('Wilmington','NC',255616);
INSERT INTO City(city_name,state_name,population) VALUES ('Montgomery','AL',254634);
INSERT INTO City(city_name,state_name,population) VALUES ('Gilbert','AZ',254114);
INSERT INTO City(city_name,state_name,population) VALUES ('Glendale','AZ',252381);
INSERT INTO City(city_name,state_name,population) VALUES ('North Las Vegas','NV',251974);
INSERT INTO City(city_name,state_name,population) VALUES ('Chesapeake','VA',244835);
INSERT INTO City(city_name,state_name,population) VALUES ('Barnstable','MA',242847);
INSERT INTO City(city_name,state_name,population) VALUES ('Norfolk','VA',242742);
INSERT INTO City(city_name,state_name,population) VALUES ('Fremont','CA',241110);
INSERT INTO City(city_name,state_name,population) VALUES ('Kennewick','WA',240735);
INSERT INTO City(city_name,state_name,population) VALUES ('Garland','TX',239928);
INSERT INTO City(city_name,state_name,population) VALUES ('Irving','TX',239798);
INSERT INTO City(city_name,state_name,population) VALUES ('Visalia','CA',237386);
INSERT INTO City(city_name,state_name,population) VALUES ('Atlantic City','NJ',237054);
INSERT INTO City(city_name,state_name,population) VALUES ('Paradise','NV',235087);
INSERT INTO City(city_name,state_name,population) VALUES ('Nashua','NH',233917);
INSERT INTO City(city_name,state_name,population) VALUES ('Arlington','VA',233464);
INSERT INTO City(city_name,state_name,population) VALUES ('Hialeah','FL',233339);
INSERT INTO City(city_name,state_name,population) VALUES ('York','PA',233184);
INSERT INTO City(city_name,state_name,population) VALUES ('Evansville','IN',230427);
INSERT INTO City(city_name,state_name,population) VALUES ('Avondale','AZ',227289);
INSERT INTO City(city_name,state_name,population) VALUES ('Brownsville','TX',227239);
INSERT INTO City(city_name,state_name,population) VALUES ('Gulfport','MS',220987);
INSERT INTO City(city_name,state_name,population) VALUES ('Appleton','WI',220570);
INSERT INTO City(city_name,state_name,population) VALUES ('Bremerton','WA',218400);
INSERT INTO City(city_name,state_name,population) VALUES ('Hickory','NC',218323);
INSERT INTO City(city_name,state_name,population) VALUES ('Tacoma','WA',217827);
INSERT INTO City(city_name,state_name,population) VALUES ('San Bernardino','CA',215784);
INSERT INTO City(city_name,state_name,population) VALUES ('College Station','TX',215243);
INSERT INTO City(city_name,state_name,population) VALUES ('Kalamazoo','MI',215193);
INSERT INTO City(city_name,state_name,population) VALUES ('Thousand Oaks','CA',215029);
INSERT INTO City(city_name,state_name,population) VALUES ('Roanoke','VA',214674);
INSERT INTO City(city_name,state_name,population) VALUES ('Fontana','CA',214547);
INSERT INTO City(city_name,state_name,population) VALUES ('Moreno Valley','CA',213055);
INSERT INTO City(city_name,state_name,population) VALUES ('North Port','FL',209070);
INSERT INTO City(city_name,state_name,population) VALUES ('Fargo','ND',208675);
INSERT INTO City(city_name,state_name,population) VALUES ('Green Bay','WI',207557);
INSERT INTO City(city_name,state_name,population) VALUES ('Spring Valley','NV',207127);
INSERT INTO City(city_name,state_name,population) VALUES ('Amarillo','TX',205603);
INSERT INTO City(city_name,state_name,population) VALUES ('Portland','ME',203969);
INSERT INTO City(city_name,state_name,population) VALUES ('Santa Barbara','CA',202401);
INSERT INTO City(city_name,state_name,population) VALUES ('Gainesville','FL',202335);
INSERT INTO City(city_name,state_name,population) VALUES ('Olympia','WA',200915);
INSERT INTO City(city_name,state_name,population) VALUES ('Frisco','TX',200490);
INSERT INTO City(city_name,state_name,population) VALUES ('Yonkers','NY',200370);
INSERT INTO City(city_name,state_name,population) VALUES ('Norwich','CT',200289);
INSERT INTO City(city_name,state_name,population) VALUES ('Glendale','CA',199303);
INSERT INTO City(city_name,state_name,population) VALUES ('Huntington Beach','CA',199223);
INSERT INTO City(city_name,state_name,population) VALUES ('Deltona','FL',198361);
INSERT INTO City(city_name,state_name,population) VALUES ('Aurora','IL',197757);
INSERT INTO City(city_name,state_name,population) VALUES ('Tempe','AZ',195805);
INSERT INTO City(city_name,state_name,population) VALUES ('Overland Park','KS',195494);
INSERT INTO City(city_name,state_name,population) VALUES ('Grand Prairie','TX',194543);
INSERT INTO City(city_name,state_name,population) VALUES ('Sunrise Manor','NV',193781);
INSERT INTO City(city_name,state_name,population) VALUES ('Waco','TX',192315);
INSERT INTO City(city_name,state_name,population) VALUES ('Salinas','CA',190972);
INSERT INTO City(city_name,state_name,population) VALUES ('Waterbury','CT',189614);
INSERT INTO City(city_name,state_name,population) VALUES ('Clarksville','TN',188746);
INSERT INTO City(city_name,state_name,population) VALUES ('Cedar Rapids','IA',188038);
INSERT INTO City(city_name,state_name,population) VALUES ('Sioux Falls','SD',187239);
INSERT INTO City(city_name,state_name,population) VALUES ('Huntington','WV',186034);
INSERT INTO City(city_name,state_name,population) VALUES ('Ontario','CA',185010);
INSERT INTO City(city_name,state_name,population) VALUES ('Hagerstown','MD',184755);
INSERT INTO City(city_name,state_name,population) VALUES ('Erie','PA',184484);
INSERT INTO City(city_name,state_name,population) VALUES ('Vancouver','WA',184463);
INSERT INTO City(city_name,state_name,population) VALUES ('Nampa','ID',184428);
INSERT INTO City(city_name,state_name,population) VALUES ('Spartanburg','SC',182701);
INSERT INTO City(city_name,state_name,population) VALUES ('Gastonia','NC',182581);
INSERT INTO City(city_name,state_name,population) VALUES ('Fort Lauderdale','FL',182437);
INSERT INTO City(city_name,state_name,population) VALUES ('Lorain','OH',180279);
INSERT INTO City(city_name,state_name,population) VALUES ('Murfreesboro','TN',179951);
INSERT INTO City(city_name,state_name,population) VALUES ('High Point','NC',179913);
INSERT INTO City(city_name,state_name,population) VALUES ('Newport News','VA',179225);
INSERT INTO City(city_name,state_name,population) VALUES ('Rancho Cucamonga','CA',177603);
INSERT INTO City(city_name,state_name,population) VALUES ('Hemet','CA',177253);
INSERT INTO City(city_name,state_name,population) VALUES ('Santa Cruz','CA',176428);
INSERT INTO City(city_name,state_name,population) VALUES ('Danbury','CT',176030);
INSERT INTO City(city_name,state_name,population) VALUES ('Peoria','AZ',175961);
INSERT INTO City(city_name,state_name,population) VALUES ('Oceanside','CA',175742);
INSERT INTO City(city_name,state_name,population) VALUES ('Elk Grove','CA',174775);
INSERT INTO City(city_name,state_name,population) VALUES ('Pembroke Pines','FL',173591);
INSERT INTO City(city_name,state_name,population) VALUES ('Vallejo','CA',173256);
INSERT INTO City(city_name,state_name,population) VALUES ('Garden Grove','CA',171644);
INSERT INTO City(city_name,state_name,population) VALUES ('Enterprise','NV',171108);
INSERT INTO City(city_name,state_name,population) VALUES ('Medford','OR',170876);
INSERT INTO City(city_name,state_name,population) VALUES ('Cary','NC',170282);
INSERT INTO City(city_name,state_name,population) VALUES ('Marysville','WA',170009);
INSERT INTO City(city_name,state_name,population) VALUES ('Corona','CA',169868);
INSERT INTO City(city_name,state_name,population) VALUES ('Ocala','FL',169383);
INSERT INTO City(city_name,state_name,population) VALUES ('Fredericksburg','VA',168909);
INSERT INTO City(city_name,state_name,population) VALUES ('Gainesville','GA',167371);
INSERT INTO City(city_name,state_name,population) VALUES ('Manchester','NH',162877);
INSERT INTO City(city_name,state_name,population) VALUES ('Bayamón','PR',161034);
INSERT INTO City(city_name,state_name,population) VALUES ('Champaign','IL',159443);
INSERT INTO City(city_name,state_name,population) VALUES ('Alexandria','VA',159428);
INSERT INTO City(city_name,state_name,population) VALUES ('Hayward','CA',159203);
INSERT INTO City(city_name,state_name,population) VALUES ('Springfield','IL',158509);
INSERT INTO City(city_name,state_name,population) VALUES ('Lakewood','CO',157935);
INSERT INTO City(city_name,state_name,population) VALUES ('Lafayette','IN',157820);
INSERT INTO City(city_name,state_name,population) VALUES ('Frederick','MD',156787);
INSERT INTO City(city_name,state_name,population) VALUES ('Lake Charles','LA',156181);
INSERT INTO City(city_name,state_name,population) VALUES ('Odessa','TX',155998);
INSERT INTO City(city_name,state_name,population) VALUES ('Tuscaloosa','AL',155499);
INSERT INTO City(city_name,state_name,population) VALUES ('Warner Robins','GA',155140);
INSERT INTO City(city_name,state_name,population) VALUES ('Palmdale','CA',155079);
INSERT INTO City(city_name,state_name,population) VALUES ('Hollywood','FL',154817);
INSERT INTO City(city_name,state_name,population) VALUES ('Midland','TX',154793);
INSERT INTO City(city_name,state_name,population) VALUES ('Leesburg','FL',154574);
INSERT INTO City(city_name,state_name,population) VALUES ('Port Arthur','TX',154468);
INSERT INTO City(city_name,state_name,population) VALUES ('Muskegon','MI',153565);
INSERT INTO City(city_name,state_name,population) VALUES ('Macon','GA',153159);
INSERT INTO City(city_name,state_name,population) VALUES ('Kansas City','KS',152960);
INSERT INTO City(city_name,state_name,population) VALUES ('Sunnyvale','CA',152703);
INSERT INTO City(city_name,state_name,population) VALUES ('Pomona','CA',151691);
INSERT INTO City(city_name,state_name,population) VALUES ('Escondido','CA',151625);
INSERT INTO City(city_name,state_name,population) VALUES ('Pasadena','TX',151227);
INSERT INTO City(city_name,state_name,population) VALUES ('New Bedford','MA',149910);
INSERT INTO City(city_name,state_name,population) VALUES ('Fairfield','CA',148683);
INSERT INTO City(city_name,state_name,population) VALUES ('Naperville','IL',148449);
INSERT INTO City(city_name,state_name,population) VALUES ('Bellevue','WA',148164);
INSERT INTO City(city_name,state_name,population) VALUES ('Binghamton','NY',148145);
INSERT INTO City(city_name,state_name,population) VALUES ('Elkhart','IN',147567);
INSERT INTO City(city_name,state_name,population) VALUES ('Topeka','KS',147458);
INSERT INTO City(city_name,state_name,population) VALUES ('Joliet','IL',147344);
INSERT INTO City(city_name,state_name,population) VALUES ('Beaumont','TX',146091);
INSERT INTO City(city_name,state_name,population) VALUES ('Paterson','NJ',145233);
INSERT INTO City(city_name,state_name,population) VALUES ('Merced','CA',145149);
INSERT INTO City(city_name,state_name,population) VALUES ('Pueblo','CO',143932);
INSERT INTO City(city_name,state_name,population) VALUES ('Tyler','TX',143796);
INSERT INTO City(city_name,state_name,population) VALUES ('Torrance','CA',143592);
INSERT INTO City(city_name,state_name,population) VALUES ('Yuma','AZ',142847);
INSERT INTO City(city_name,state_name,population) VALUES ('Metairie','LA',142135);
INSERT INTO City(city_name,state_name,population) VALUES ('Surprise','AZ',141664);
INSERT INTO City(city_name,state_name,population) VALUES ('Columbia','MO',141645);
INSERT INTO City(city_name,state_name,population) VALUES ('Athens','GA',141532);
INSERT INTO City(city_name,state_name,population) VALUES ('Roseville','CA',141500);
INSERT INTO City(city_name,state_name,population) VALUES ('Thornton','CO',141464);
INSERT INTO City(city_name,state_name,population) VALUES ('Miramar','FL',141191);
INSERT INTO City(city_name,state_name,population) VALUES ('Pasadena','CA',141029);
INSERT INTO City(city_name,state_name,population) VALUES ('Mesquite','TX',140937);
INSERT INTO City(city_name,state_name,population) VALUES ('Olathe','KS',140545);
INSERT INTO City(city_name,state_name,population) VALUES ('Santa Maria','CA',140545);
INSERT INTO City(city_name,state_name,population) VALUES ('Houma','LA',140469);
INSERT INTO City(city_name,state_name,population) VALUES ('Carrollton','TX',139248);
INSERT INTO City(city_name,state_name,population) VALUES ('Grand Junction','CO',139143);
INSERT INTO City(city_name,state_name,population) VALUES ('Charleston','WV',138706);
INSERT INTO City(city_name,state_name,population) VALUES ('Orange','CA',138669);
INSERT INTO City(city_name,state_name,population) VALUES ('Fullerton','CA',138632);
INSERT INTO City(city_name,state_name,population) VALUES ('Greeley','CO',137810);
INSERT INTO City(city_name,state_name,population) VALUES ('Carolina','PR',136771);
INSERT INTO City(city_name,state_name,population) VALUES ('Las Cruces','NM',136254);
INSERT INTO City(city_name,state_name,population) VALUES ('Panama City','FL',136133);
INSERT INTO City(city_name,state_name,population) VALUES ('Harlingen','TX',136037);
INSERT INTO City(city_name,state_name,population) VALUES ('West Valley City','UT',135248);
INSERT INTO City(city_name,state_name,population) VALUES ('Hampton','VA',134510);
INSERT INTO City(city_name,state_name,population) VALUES ('Warren','MI',133943);
INSERT INTO City(city_name,state_name,population) VALUES ('Mauldin','SC',133872);
INSERT INTO City(city_name,state_name,population) VALUES ('Bloomington','IL',133846);
INSERT INTO City(city_name,state_name,population) VALUES ('Coral Springs','FL',133759);
INSERT INTO City(city_name,state_name,population) VALUES ('Round Rock','TX',133372);
INSERT INTO City(city_name,state_name,population) VALUES ('Yakima','WA',133191);
INSERT INTO City(city_name,state_name,population) VALUES ('Sterling Heights','MI',132438);
INSERT INTO City(city_name,state_name,population) VALUES ('Kent','WA',132319);
INSERT INTO City(city_name,state_name,population) VALUES ('Burlington','NC',131043);
INSERT INTO City(city_name,state_name,population) VALUES ('Bellingham','WA',130641);
INSERT INTO City(city_name,state_name,population) VALUES ('Santa Clara','CA',130365);
INSERT INTO City(city_name,state_name,population) VALUES ('Racine','WI',130142);
INSERT INTO City(city_name,state_name,population) VALUES ('Greenville','NC',130118);
INSERT INTO City(city_name,state_name,population) VALUES ('Stamford','CT',129638);
INSERT INTO City(city_name,state_name,population) VALUES ('Elizabeth','NJ',129216);
INSERT INTO City(city_name,state_name,population) VALUES ('Johnson City','TN',127571);
INSERT INTO City(city_name,state_name,population) VALUES ('Lynchburg','VA',126814);
INSERT INTO City(city_name,state_name,population) VALUES ('Simi Valley','CA',126589);
INSERT INTO City(city_name,state_name,population) VALUES ('Fort Smith','AR',125354);
INSERT INTO City(city_name,state_name,population) VALUES ('Kenosha','WI',124972);
INSERT INTO City(city_name,state_name,population) VALUES ('Norman','OK',124880);
INSERT INTO City(city_name,state_name,population) VALUES ('South Lyon','MI',124694);
INSERT INTO City(city_name,state_name,population) VALUES ('Boulder','CO',124345);
INSERT INTO City(city_name,state_name,population) VALUES ('Abilene','TX',123420);
INSERT INTO City(city_name,state_name,population) VALUES ('Lehigh Acres','FL',123378);
INSERT INTO City(city_name,state_name,population) VALUES ('Pearland','TX',122460);
INSERT INTO City(city_name,state_name,population) VALUES ('Berkeley','CA',121363);
INSERT INTO City(city_name,state_name,population) VALUES ('Richardson','TX',121323);
INSERT INTO City(city_name,state_name,population) VALUES ('Redding','CA',121313);
INSERT INTO City(city_name,state_name,population) VALUES ('Arvada','CO',121272);
INSERT INTO City(city_name,state_name,population) VALUES ('East Los Angeles','CA',121187);
INSERT INTO City(city_name,state_name,population) VALUES ('St. George','UT',120899);
INSERT INTO City(city_name,state_name,population) VALUES ('Billings','MT',120728);
INSERT INTO City(city_name,state_name,population) VALUES ('Yuba City','CA',120456);
INSERT INTO City(city_name,state_name,population) VALUES ('Rochester','MN',119942);
INSERT INTO City(city_name,state_name,population) VALUES ('Leominster','MA',119690);
INSERT INTO City(city_name,state_name,population) VALUES ('Kingsport','TN',119666);
INSERT INTO City(city_name,state_name,population) VALUES ('Duluth','MN',119476);
INSERT INTO City(city_name,state_name,population) VALUES ('Rock Hill','SC',119105);
INSERT INTO City(city_name,state_name,population) VALUES ('Gilroy','CA',118993);
INSERT INTO City(city_name,state_name,population) VALUES ('Cambridge','MA',118927);
INSERT INTO City(city_name,state_name,population) VALUES ('Sugar Land','TX',118488);
INSERT INTO City(city_name,state_name,population) VALUES ('Texas City','TX',118169);
INSERT INTO City(city_name,state_name,population) VALUES ('Iowa City','IA',118041);
INSERT INTO City(city_name,state_name,population) VALUES ('Saginaw','MI',117958);
INSERT INTO City(city_name,state_name,population) VALUES ('Chico','CA',117668);
INSERT INTO City(city_name,state_name,population) VALUES ('Dover','DE',117282);
INSERT INTO City(city_name,state_name,population) VALUES ('Clearwater','FL',116946);
INSERT INTO City(city_name,state_name,population) VALUES ('Coeur d''Alene','ID',116834);
INSERT INTO City(city_name,state_name,population) VALUES ('Seaside','CA',116720);
INSERT INTO City(city_name,state_name,population) VALUES ('Independence','MO',116672);
INSERT INTO City(city_name,state_name,population) VALUES ('West Jordan','UT',116480);
INSERT INTO City(city_name,state_name,population) VALUES ('Brandon','FL',115911);
INSERT INTO City(city_name,state_name,population) VALUES ('Bloomington','IN',115884);
INSERT INTO City(city_name,state_name,population) VALUES ('El Monte','CA',115487);
INSERT INTO City(city_name,state_name,population) VALUES ('North Charleston','SC',115382);
INSERT INTO City(city_name,state_name,population) VALUES ('Carlsbad','CA',115382);
INSERT INTO City(city_name,state_name,population) VALUES ('St. Cloud','MN',115028);
INSERT INTO City(city_name,state_name,population) VALUES ('Temecula','CA',114761);
INSERT INTO City(city_name,state_name,population) VALUES ('Clovis','CA',114584);
INSERT INTO City(city_name,state_name,population) VALUES ('Meridian','ID',114161);
INSERT INTO City(city_name,state_name,population) VALUES ('The Woodlands','TX',113819);
INSERT INTO City(city_name,state_name,population) VALUES ('Ponce','PR',113401);
INSERT INTO City(city_name,state_name,population) VALUES ('Westminster','CO',113166);
INSERT INTO City(city_name,state_name,population) VALUES ('Costa Mesa','CA',113003);
INSERT INTO City(city_name,state_name,population) VALUES ('Monroe','LA',112891);
INSERT INTO City(city_name,state_name,population) VALUES ('Utica','NY',112650);
INSERT INTO City(city_name,state_name,population) VALUES ('Pompano Beach','FL',112118);
INSERT INTO City(city_name,state_name,population) VALUES ('West Palm Beach','FL',111955);
INSERT INTO City(city_name,state_name,population) VALUES ('Waterloo','IA',111631);
INSERT INTO City(city_name,state_name,population) VALUES ('Everett','WA',111475);
INSERT INTO City(city_name,state_name,population) VALUES ('El Centro','CA',111425);
INSERT INTO City(city_name,state_name,population) VALUES ('Santa Fe','NM',111269);
INSERT INTO City(city_name,state_name,population) VALUES ('Downey','CA',111126);
INSERT INTO City(city_name,state_name,population) VALUES ('Spring Hill','FL',111076);
INSERT INTO City(city_name,state_name,population) VALUES ('Lowell','MA',110997);
INSERT INTO City(city_name,state_name,population) VALUES ('Centennial','CO',110937);
INSERT INTO City(city_name,state_name,population) VALUES ('Elgin','IL',110849);
INSERT INTO City(city_name,state_name,population) VALUES ('Richmond','CA',110567);
INSERT INTO City(city_name,state_name,population) VALUES ('Broken Arrow','OK',110198);
INSERT INTO City(city_name,state_name,population) VALUES ('Miami Gardens','FL',110001);
INSERT INTO City(city_name,state_name,population) VALUES ('Bend','OR',109802);
INSERT INTO City(city_name,state_name,population) VALUES ('Burlington','VT',109763);
INSERT INTO City(city_name,state_name,population) VALUES ('Jurupa Valley','CA',109527);
INSERT INTO City(city_name,state_name,population) VALUES ('Sandy Springs','GA',109452);
INSERT INTO City(city_name,state_name,population) VALUES ('Gresham','OR',109381);
INSERT INTO City(city_name,state_name,population) VALUES ('Lewisville','TX',109212);
INSERT INTO City(city_name,state_name,population) VALUES ('Hillsboro','OR',109128);
INSERT INTO City(city_name,state_name,population) VALUES ('San Buenaventura','CA',109106);
INSERT INTO City(city_name,state_name,population) VALUES ('Jacksonville','NC',108856);
INSERT INTO City(city_name,state_name,population) VALUES ('Pottstown','PA',108758);
INSERT INTO City(city_name,state_name,population) VALUES ('Inglewood','CA',108151);
INSERT INTO City(city_name,state_name,population) VALUES ('League City','TX',107536);
INSERT INTO City(city_name,state_name,population) VALUES ('Eau Claire','WI',107404);
INSERT INTO City(city_name,state_name,population) VALUES ('Turlock','CA',107317);
INSERT INTO City(city_name,state_name,population) VALUES ('Temple','TX',107258);
INSERT INTO City(city_name,state_name,population) VALUES ('Sioux City','IA',106455);
INSERT INTO City(city_name,state_name,population) VALUES ('Salisbury','MD',106447);
INSERT INTO City(city_name,state_name,population) VALUES ('Davie','FL',106306);
INSERT INTO City(city_name,state_name,population) VALUES ('Daly City','CA',106280);
INSERT INTO City(city_name,state_name,population) VALUES ('Highlands Ranch','CO',105631);
INSERT INTO City(city_name,state_name,population) VALUES ('Allen','TX',105623);
INSERT INTO City(city_name,state_name,population) VALUES ('West Covina','CA',105101);
INSERT INTO City(city_name,state_name,population) VALUES ('Sparks','NV',105006);
INSERT INTO City(city_name,state_name,population) VALUES ('Wichita Falls','TX',104683);
INSERT INTO City(city_name,state_name,population) VALUES ('San Mateo','CA',104430);
INSERT INTO City(city_name,state_name,population) VALUES ('Columbia','MD',103991);
INSERT INTO City(city_name,state_name,population) VALUES ('Norwalk','CA',103949);
INSERT INTO City(city_name,state_name,population) VALUES ('Rialto','CA',103526);
INSERT INTO City(city_name,state_name,population) VALUES ('Manteca','CA',103420);
INSERT INTO City(city_name,state_name,population) VALUES ('Arden-Arcade','CA',102864);
INSERT INTO City(city_name,state_name,population) VALUES ('El Cajon','CA',102708);
INSERT INTO City(city_name,state_name,population) VALUES ('Burbank','CA',102511);
INSERT INTO City(city_name,state_name,population) VALUES ('Longmont','CO',102474);
INSERT INTO City(city_name,state_name,population) VALUES ('Renton','WA',101751);
INSERT INTO City(city_name,state_name,population) VALUES ('Vista','CA',101638);
INSERT INTO City(city_name,state_name,population) VALUES ('Logan','UT',101616);
INSERT INTO City(city_name,state_name,population) VALUES ('Prescott Valley','AZ',101539);
INSERT INTO City(city_name,state_name,population) VALUES ('Vacaville','CA',101444);
INSERT INTO City(city_name,state_name,population) VALUES ('Edinburg','TX',101170);
INSERT INTO City(city_name,state_name,population) VALUES ('Carmel','IN',101068);
INSERT INTO City(city_name,state_name,population) VALUES ('Spokane Valley','WA',101060);
INSERT INTO City(city_name,state_name,population) VALUES ('San Angelo','TX',101004);
INSERT INTO City(city_name,state_name,population) VALUES ('La Crosse','WI',100693);
INSERT INTO City(city_name,state_name,population) VALUES ('Idaho Falls','ID',100442);
INSERT INTO City(city_name,state_name,population) VALUES ('Holland','MI',100432);
INSERT INTO City(city_name,state_name,population) VALUES ('Charlottesville','VA',100416);
INSERT INTO City(city_name,state_name,population) VALUES ('Longview','TX',100330);
INSERT INTO City(city_name,state_name,population) VALUES ('Tracy','CA',100049);
